### ISSUE TITLE
Math Lecture Notes Awesome List

### ISSUE THREAD

**Issue by mostafatouny** [alexrutar/UWaterloo-Course-Notes#1]
Hello,
There is a curated list for math lecture notes [here](https://github.com/rossant/awesome-math). I believe it is a good idea to add your repo there.

**Comment by alexrutar** [comment]
Thank you for your suggestion! Unfortunately, due to the incomplete nature of the notes in this repository, I would prefer not to intentionally self-promote my content.

If you maintain this list, you may feel free to add my repository there, but I will not initialize this process myself.
